### ISSUE TITLE
Implement io.ReadWriter on Kinesumer type

### ISSUE THREAD

**Issue by ejholmes** [remind101/kinesumer#15]
It would be pretty nice if Kinesummer implemented the [io.ReadWriter](http://golang.org/pkg/io/#ReadWriter) interface so you can treat kinesis streams just like any other []byte stream.

**Comment by ghost** [comment]
How would it deal with record boundaries and records arriving out of order due to multiple shards?

**Comment by sanjayprabhu** [comment]
For anything important, we should have a separate reader for each shard. Multiplexing shards is dangerous for exactly that reason.
